export type WordAnnotation = {
  text: string
  role: string
}

export const annotationsMap: Record<string, WordAnnotation[]> = {
  'cte-lv1-01': [
    { text: 'She', role: '主语' },
    { text: 'gets up', role: '谓语' },
    { text: 'at', role: '介词' },
    { text: 'seven', role: '状语(时间)' },
    { text: 'every', role: '定语' },
    { text: 'morning', role: '状语(时间)' },
    { text: '.', role: '标点' },
  ],
  'cte-lv1-02': [
    { text: 'I', role: '主语' },
    { text: 'am', role: '助动词' },
    { text: 'reading', role: '谓语' },
    { text: 'a', role: '冠词' },
    { text: 'book', role: '宾语' },
    { text: '.', role: '标点' },
  ],
  'cte-lv1-03': [
    { text: 'He', role: '主语' },
    { text: 'went', role: '谓语' },
    { text: 'to', role: '介词' },
    { text: 'Beijing', role: '状语(地点)' },
    { text: 'yesterday', role: '状语(时间)' },
    { text: '.', role: '标点' },
  ],
  'cte-lv1-04': [
    { text: 'There', role: '引导词' },
    { text: 'is', role: '谓语' },
    { text: 'a', role: '冠词' },
    { text: 'book', role: '主语' },
    { text: 'and', role: '连词' },
    { text: 'two', role: '定语' },
    { text: 'pens', role: '主语' },
    { text: 'on', role: '介词' },
    { text: 'the', role: '冠词' },
    { text: 'desk', role: '状语(地点)' },
    { text: '.', role: '标点' },
  ],
  'cte-lv1-05': [
    { text: 'Do', role: '助动词' },
    { text: 'you', role: '主语' },
    { text: 'like', role: '谓语' },
    { text: 'drinking', role: '宾语' },
    { text: 'tea', role: '宾语' },
    { text: '?', role: '标点' },
  ],
  'cte-lv1-06': [
    { text: 'She', role: '主语' },
    { text: 'will', role: '助动词' },
    { text: 'come', role: '谓语' },
    { text: 'to', role: '介词' },
    { text: 'the', role: '冠词' },
    { text: 'party', role: '状语(目的)' },
    { text: 'tomorrow', role: '状语(时间)' },
    { text: '.', role: '标点' },
  ],
  'cte-lv1-07': [
    { text: 'They', role: '主语' },
    { text: 'can', role: '情态动词' },
    { text: 'play', role: '谓语' },
    { text: 'basketball', role: '宾语' },
    { text: '.', role: '标点' },
  ],
  'cte-lv1-08': [
    { text: 'Please', role: '感叹词' },
    { text: 'open', role: '谓语' },
    { text: 'the', role: '冠词' },
    { text: 'door', role: '宾语' },
    { text: '.', role: '标点' },
  ],
  'cte-lv1-09': [
    { text: 'This', role: '主语' },
    { text: 'is', role: '谓语' },
    { text: 'my', role: '定语' },
    { text: 'book', role: '表语' },
    { text: 'and', role: '连词' },
    { text: 'that', role: '主语' },
    { text: 'is', role: '谓语' },
    { text: 'yours', role: '表语' },
    { text: '.', role: '标点' },
  ],
  'cte-lv1-10': [
    { text: 'There', role: '引导词' },
    { text: 'is', role: '谓语' },
    { text: 'much', role: '定语' },
    { text: 'water', role: '主语' },
    { text: 'in', role: '介词' },
    { text: 'the', role: '冠词' },
    { text: 'bottle', role: '状语(地点)' },
    { text: '.', role: '标点' },
  ],
  'cte-lv1-11': [
    { text: 'Where', role: '疑问词' },
    { text: 'does', role: '助动词' },
    { text: 'she', role: '主语' },
    { text: 'live', role: '谓语' },
    { text: '?', role: '标点' },
  ],
  'cte-lv1-12': [
    { text: 'We', role: '主语' },
    { text: 'were', role: '助动词' },
    { text: 'having', role: '谓语' },
    { text: 'dinner', role: '宾语' },
    { text: 'at', role: '介词' },
    { text: 'eight', role: '状语(时间)' },
    { text: 'yesterday', role: '状语(时间)' },
    { text: '.', role: '标点' },
  ],
  'cte-lv1-13': [
    { text: 'What', role: '感叹词' },
    { text: 'a', role: '冠词' },
    { text: 'beautiful', role: '定语' },
    { text: 'flower', role: '主语' },
    { text: 'it', role: '主语' },
    { text: 'is', role: '谓语' },
    { text: '!', role: '标点' },
  ],
  'cte-lv1-14': [
    { text: 'He', role: '主语' },
    { text: 'is', role: '谓语' },
    { text: 'a', role: '冠词' },
    { text: 'good', role: '定语' },
    { text: 'student', role: '表语' },
    { text: ',', role: '标点' },
    { text: "isn't", role: '助动词' },
    { text: 'he', role: '主语' },
    { text: '?', role: '标点' },
  ],
  'cte-lv1-15': [
    { text: 'She', role: '主语' },
    { text: 'always', role: '状语(频率)' },
    { text: 'gets', role: '谓语' },
    { text: 'up', role: '谓语' },
    { text: 'early', role: '状语(方式)' },
    { text: '.', role: '标点' },
  ],
  'cte-lv1-16': [
    { text: 'I', role: '主语' },
    { text: 'like', role: '谓语' },
    { text: 'reading', role: '宾语' },
    { text: 'books', role: '宾语' },
    { text: ',', role: '标点' },
    { text: 'but', role: '连词' },
    { text: 'my', role: '定语' },
    { text: 'brother', role: '主语' },
    { text: 'likes', role: '谓语' },
    { text: 'watching', role: '宾语' },
    { text: 'TV', role: '宾语' },
    { text: '.', role: '标点' },
  ],
  'cte-lv1-17': [
    { text: 'We', role: '主语' },
    { text: 'are going to', role: '助动词' },
    { text: 'go', role: '谓语' },
    { text: 'camping', role: '状语(目的)' },
    { text: 'this', role: '定语' },
    { text: 'weekend', role: '状语(时间)' },
    { text: '.', role: '标点' },
  ],
  'cte-lv1-18': [
    { text: 'How', role: '感叹词' },
    { text: 'fast', role: '状语' },
    { text: 'he', role: '主语' },
    { text: 'runs', role: '谓语' },
    { text: '!', role: '标点' },
  ],
  'cte-lv1-19': [
    { text: 'She', role: '主语' },
    { text: 'is', role: '谓语' },
    { text: 'not', role: '否定词' },
    { text: 'at', role: '介词' },
    { text: 'home', role: '表语' },
    { text: ',', role: '标点' },
    { text: 'is', role: '助动词' },
    { text: 'she', role: '主语' },
    { text: '?', role: '标点' },
  ],
  'cte-lv1-20': [
    { text: 'They', role: '主语' },
    { text: "didn't", role: '助动词' },
    { text: 'go', role: '谓语' },
    { text: 'to', role: '介词' },
    { text: 'school', role: '状语(地点)' },
    { text: 'yesterday', role: '状语(时间)' },
    { text: '.', role: '标点' },
  ],
  'cte-lv2-01': [
    { text: 'I', role: '主语' },
    { text: 'have been', role: '谓语' },
    { text: 'to', role: '介词' },
    { text: 'Beijing', role: '状语(地点)' },
    { text: 'twice', role: '状语(次数)' },
    { text: '.', role: '标点' },
  ],
  'cte-lv2-02': [
    { text: 'This', role: '主语' },
    { text: 'letter', role: '主语' },
    { text: 'is', role: '助动词' },
    { text: 'written', role: '谓语' },
    { text: 'in', role: '介词' },
    { text: 'English', role: '状语(方式)' },
    { text: '.', role: '标点' },
  ],
  'cte-lv2-03': [
    { text: 'She', role: '主语' },
    { text: 'is', role: '谓语' },
    { text: 'smarter', role: '表语' },
    { text: 'than', role: '连词' },
    { text: 'her', role: '定语' },
    { text: 'sister', role: '比较对象' },
    { text: '.', role: '标点' },
  ],
  'cte-lv2-04': [
    { text: 'He', role: '主语' },
    { text: 'is', role: '谓语' },
    { text: 'the', role: '冠词' },
    { text: 'tallest', role: '表语' },
    { text: 'student', role: '表语' },
    { text: 'in', role: '介词' },
    { text: 'the', role: '冠词' },
    { text: 'class', role: '状语(范围)' },
    { text: '.', role: '标点' },
  ],
  'cte-lv2-05': [
    { text: 'You', role: '主语' },
    { text: 'should', role: '情态动词' },
    { text: 'drink', role: '谓语' },
    { text: 'more', role: '定语' },
    { text: 'water', role: '宾语' },
    { text: '.', role: '标点' },
  ],
  'cte-lv2-06': [
    { text: 'I', role: '主语' },
    { text: 'decided', role: '谓语' },
    { text: 'to', role: '不定式符号' },
    { text: 'learn', role: '宾语' },
    { text: 'a', role: '冠词' },
    { text: 'new', role: '定语' },
    { text: 'language', role: '宾语' },
    { text: '.', role: '标点' },
  ],
  'cte-lv2-07': [
    { text: 'I', role: '主语' },
    { text: 'enjoy', role: '谓语' },
    { text: 'swimming', role: '宾语' },
    { text: '.', role: '标点' },
  ],
  'cte-lv2-08': [
    { text: 'She', role: '主语' },
    { text: 'is', role: '谓语' },
    { text: 'so', role: '状语(程度)' },
    { text: 'smart', role: '表语' },
    { text: 'that', role: '连词' },
    { text: 'everyone', role: '主语' },
    { text: 'likes', role: '谓语' },
    { text: 'her', role: '宾语' },
    { text: '.', role: '标点' },
  ],
  'cte-lv2-09': [
    { text: 'The', role: '冠词' },
    { text: 'box', role: '主语' },
    { text: 'is', role: '谓语' },
    { text: 'too', role: '状语(程度)' },
    { text: 'heavy', role: '表语' },
    { text: 'for', role: '介词' },
    { text: 'me', role: '宾语' },
    { text: 'to', role: '不定式符号' },
    { text: 'carry', role: '补语' },
    { text: '.', role: '标点' },
  ],
  'cte-lv2-10': [
    { text: 'The', role: '冠词' },
    { text: 'work', role: '主语' },
    { text: 'has been', role: '助动词' },
    { text: 'finished', role: '谓语' },
    { text: '.', role: '标点' },
  ],
  'cte-lv2-11': [
    { text: 'I', role: '主语' },
    { text: 'have been', role: '助动词' },
    { text: 'studying', role: '谓语' },
    { text: 'English', role: '宾语' },
    { text: 'for', role: '介词' },
    { text: 'two', role: '定语' },
    { text: 'hours', role: '状语(时长)' },
    { text: '.', role: '标点' },
  ],
  'cte-lv2-12': [
    { text: 'When', role: '连词' },
    { text: 'we', role: '主语' },
    { text: 'arrived', role: '谓语' },
    { text: ',', role: '标点' },
    { text: 'the', role: '冠词' },
    { text: 'train', role: '主语' },
    { text: 'had', role: '助动词' },
    { text: 'already', role: '状语(时间)' },
    { text: 'left', role: '谓语' },
    { text: '.', role: '标点' },
  ],
  'cte-lv2-13': [
    { text: 'He', role: '主语' },
    { text: 'has to', role: '情态动词' },
    { text: 'finish', role: '谓语' },
    { text: 'the', role: '冠词' },
    { text: 'work', role: '宾语' },
    { text: 'today', role: '状语(时间)' },
    { text: '.', role: '标点' },
  ],
  'cte-lv2-14': [
    { text: 'They', role: '主语' },
    { text: 'stopped', role: '谓语' },
    { text: 'talking', role: '宾语' },
    { text: 'when', role: '连词' },
    { text: 'the', role: '冠词' },
    { text: 'teacher', role: '主语' },
    { text: 'came', role: '谓语' },
    { text: 'in', role: '状语(方向)' },
    { text: '.', role: '标点' },
  ],
  'cte-lv2-15': [
    { text: 'She', role: '主语' },
    { text: 'used to', role: '情态动词' },
    { text: 'live', role: '谓语' },
    { text: 'in', role: '介词' },
    { text: 'the', role: '冠词' },
    { text: 'countryside', role: '状语(地点)' },
    { text: '.', role: '标点' },
  ],
  'cte-lv2-16': [
    { text: 'The', role: '冠词' },
    { text: 'children', role: '主语' },
    { text: 'enjoyed', role: '谓语' },
    { text: 'themselves', role: '宾语' },
    { text: 'at', role: '介词' },
    { text: 'the', role: '冠词' },
    { text: 'party', role: '状语(地点)' },
    { text: '.', role: '标点' },
  ],
  'cte-lv2-17': [
    { text: 'The', role: '冠词' },
    { text: 'new', role: '定语' },
    { text: 'bridge', role: '主语' },
    { text: 'will', role: '助动词' },
    { text: 'be', role: '助动词' },
    { text: 'completed', role: '谓语' },
    { text: 'next', role: '定语' },
    { text: 'year', role: '状语(时间)' },
    { text: '.', role: '标点' },
  ],
  'cte-lv2-18': [
    { text: 'The', role: '冠词' },
    { text: 'teacher', role: '主语' },
    { text: 'made', role: '谓语' },
    { text: 'the', role: '冠词' },
    { text: 'students', role: '宾语' },
    { text: 'read', role: '宾语补语' },
    { text: 'the', role: '冠词' },
    { text: 'text', role: '宾语' },
    { text: '.', role: '标点' },
  ],
  'cte-lv2-19': [
    { text: 'This', role: '定语' },
    { text: 'book', role: '主语' },
    { text: 'is', role: '谓语' },
    { text: 'more', role: '状语(程度)' },
    { text: 'interesting', role: '表语' },
    { text: 'than', role: '连词' },
    { text: 'that', role: '定语' },
    { text: 'one', role: '比较对象' },
    { text: '.', role: '标点' },
  ],
  'cte-lv2-20': [
    { text: 'You', role: '主语' },
    { text: 'must', role: '情态动词' },
    { text: 'not', role: '否定词' },
    { text: 'be', role: '谓语' },
    { text: 'late', role: '表语' },
    { text: '.', role: '标点' },
  ],
  'cte-lv3-01': [
    { text: 'The', role: '冠词' },
    { text: 'man', role: '主语' },
    { text: 'who', role: '关系代词' },
    { text: 'is', role: '谓语' },
    { text: 'standing', role: '谓语' },
    { text: 'there', role: '状语(地点)' },
    { text: 'is', role: '谓语' },
    { text: 'my', role: '定语' },
    { text: 'teacher', role: '表语' },
    { text: '.', role: '标点' },
  ],
  'cte-lv3-02': [
    { text: 'I', role: '主语' },
    { text: 'stayed', role: '谓语' },
    { text: 'at', role: '介词' },
    { text: 'home', role: '状语(地点)' },
    { text: 'because', role: '连词' },
    { text: 'I', role: '主语' },
    { text: 'was', role: '谓语' },
    { text: 'tired', role: '表语' },
    { text: '.', role: '标点' },
  ],
  'cte-lv3-03': [
    { text: 'Although', role: '连词' },
    { text: 'he', role: '主语' },
    { text: 'was', role: '谓语' },
    { text: 'tired', role: '表语' },
    { text: ',', role: '标点' },
    { text: 'he', role: '主语' },
    { text: 'continued', role: '谓语' },
    { text: 'working', role: '宾语' },
    { text: '.', role: '标点' },
  ],
  'cte-lv3-04': [
    { text: 'If', role: '连词' },
    { text: 'it', role: '主语' },
    { text: 'rains', role: '谓语' },
    { text: 'tomorrow', role: '状语(时间)' },
    { text: ',', role: '标点' },
    { text: 'we', role: '主语' },
    { text: 'will', role: '助动词' },
    { text: 'stay', role: '谓语' },
    { text: 'at', role: '介词' },
    { text: 'home', role: '状语(地点)' },
    { text: '.', role: '标点' },
  ],
  'cte-lv3-05': [
    { text: 'If', role: '连词' },
    { text: 'I', role: '主语' },
    { text: 'were', role: '谓语' },
    { text: 'you', role: '表语' },
    { text: ',', role: '标点' },
    { text: 'I', role: '主语' },
    { text: 'would', role: '助动词' },
    { text: 'study', role: '谓语' },
    { text: 'harder', role: '状语(方式)' },
    { text: '.', role: '标点' },
  ],
  'cte-lv3-06': [
    { text: 'Never', role: '否定词' },
    { text: 'have', role: '助动词' },
    { text: 'I', role: '主语' },
    { text: 'seen', role: '谓语' },
    { text: 'such', role: '定语' },
    { text: 'a', role: '冠词' },
    { text: 'beautiful', role: '定语' },
    { text: 'sunset', role: '宾语' },
    { text: '.', role: '标点' },
  ],
  'cte-lv3-07': [
    { text: 'It', role: '形式主语' },
    { text: 'was', role: '谓语' },
    { text: 'Tom', role: '强调部分' },
    { text: 'who', role: '关系代词' },
    { text: 'broke', role: '谓语' },
    { text: 'the', role: '冠词' },
    { text: 'window', role: '宾语' },
    { text: 'yesterday', role: '状语(时间)' },
    { text: '.', role: '标点' },
  ],
  'cte-lv3-08': [
    { text: 'He', role: '主语' },
    { text: 'said', role: '谓语' },
    { text: 'that', role: '连词' },
    { text: 'he', role: '主语' },
    { text: 'was', role: '助动词' },
    { text: 'reading', role: '谓语' },
    { text: 'a', role: '冠词' },
    { text: 'book', role: '宾语' },
    { text: '.', role: '标点' },
  ],
  'cte-lv3-09': [
    { text: 'I', role: '主语' },
    { text: "don't", role: '助动词' },
    { text: 'know', role: '谓语' },
    { text: 'where', role: '疑问词' },
    { text: 'he', role: '主语' },
    { text: 'lives', role: '谓语' },
    { text: '.', role: '标点' },
  ],
  'cte-lv3-10': [
    { text: 'That', role: '引导词' },
    { text: 'he', role: '主语' },
    { text: 'passed', role: '谓语' },
    { text: 'the', role: '冠词' },
    { text: 'exam', role: '宾语' },
    { text: 'is', role: '谓语' },
    { text: 'true', role: '表语' },
    { text: '.', role: '标点' },
  ],
  'cte-lv3-11': [
    { text: 'Hearing', role: '状语(非谓语)' },
    { text: 'the', role: '冠词' },
    { text: 'news', role: '宾语' },
    { text: ',', role: '标点' },
    { text: 'she', role: '主语' },
    { text: 'burst', role: '谓语' },
    { text: 'into', role: '介词' },
    { text: 'tears', role: '状语(结果)' },
    { text: '.', role: '标点' },
  ],
  'cte-lv3-12': [
    { text: 'I', role: '主语' },
    { text: 'wish', role: '谓语' },
    { text: 'I', role: '主语' },
    { text: 'were', role: '谓语' },
    { text: 'taller', role: '表语' },
    { text: '.', role: '标点' },
  ],
  'cte-lv3-13': [
    { text: 'My', role: '定语' },
    { text: 'father', role: '主语' },
    { text: ',', role: '标点' },
    { text: 'who', role: '关系代词' },
    { text: 'is', role: '谓语' },
    { text: 'a', role: '冠词' },
    { text: 'doctor', role: '表语' },
    { text: ',', role: '标点' },
    { text: 'works', role: '谓语' },
    { text: 'very', role: '状语(程度)' },
    { text: 'hard', role: '状语(方式)' },
    { text: '.', role: '标点' },
  ],
  'cte-lv3-14': [
    { text: 'The', role: '冠词' },
    { text: 'truth', role: '主语' },
    { text: 'is', role: '谓语' },
    { text: 'that', role: '连词' },
    { text: 'we', role: '主语' },
    { text: 'have', role: '谓语' },
    { text: 'no', role: '定语' },
    { text: 'choice', role: '宾语' },
    { text: '.', role: '标点' },
  ],
  'cte-lv3-15': [
    { text: 'The', role: '冠词' },
    { text: 'news', role: '主语' },
    { text: 'that', role: '连词' },
    { text: 'he', role: '主语' },
    { text: 'won', role: '谓语' },
    { text: 'the', role: '冠词' },
    { text: 'prize', role: '宾语' },
    { text: 'spread', role: '谓语' },
    { text: 'quickly', role: '状语(方式)' },
    { text: '.', role: '标点' },
  ],
  'cte-lv3-16': [
    { text: 'Weather', role: '逻辑主语' },
    { text: 'permitting', role: '独立主格' },
    { text: ',', role: '标点' },
    { text: 'we', role: '主语' },
    { text: 'will', role: '助动词' },
    { text: 'go', role: '谓语' },
    { text: 'camping', role: '状语(目的)' },
    { text: 'tomorrow', role: '状语(时间)' },
    { text: '.', role: '标点' },
  ],
  'cte-lv3-17': [
    { text: 'While', role: '连词' },
    { text: 'I', role: '主语' },
    { text: 'was', role: '助动词' },
    { text: 'walking', role: '谓语' },
    { text: 'home', role: '状语(方向)' },
    { text: ',', role: '标点' },
    { text: 'I', role: '主语' },
    { text: 'met', role: '谓语' },
    { text: 'an', role: '冠词' },
    { text: 'old', role: '定语' },
    { text: 'friend', role: '宾语' },
    { text: '.', role: '标点' },
  ],
  'cte-lv3-18': [
    { text: 'She', role: '主语' },
    { text: 'studies', role: '谓语' },
    { text: 'hard', role: '状语(方式)' },
    { text: 'so', role: '连词' },
    { text: 'that', role: '连词' },
    { text: 'she', role: '主语' },
    { text: 'can', role: '情态动词' },
    { text: 'pass', role: '谓语' },
    { text: 'the', role: '冠词' },
    { text: 'exam', role: '宾语' },
    { text: '.', role: '标点' },
  ],
  'cte-lv3-19': [
    { text: 'This', role: '主语' },
    { text: 'is', role: '谓语' },
    { text: 'the', role: '冠词' },
    { text: 'house', role: '表语' },
    { text: 'where', role: '关系副词' },
    { text: 'I', role: '主语' },
    { text: 'was', role: '助动词' },
    { text: 'born', role: '谓语' },
    { text: '.', role: '标点' },
  ],
  'cte-lv3-20': [
    { text: 'This', role: '主语' },
    { text: 'is', role: '谓语' },
    { text: 'the', role: '冠词' },
    { text: 'book', role: '表语' },
    { text: 'that', role: '关系代词' },
    { text: 'I', role: '主语' },
    { text: 'bought', role: '谓语' },
    { text: '.', role: '标点' },
  ],
}

export const roleColors: Record<string, string> = {
  '主语': 'text-blue-600 dark:text-blue-400 bg-blue-50 dark:bg-blue-900/20',
  '谓语': 'text-rose-600 dark:text-rose-400 bg-rose-50 dark:bg-rose-900/20',
  '宾语': 'text-green-600 dark:text-green-400 bg-green-50 dark:bg-green-900/20',
  '表语': 'text-purple-600 dark:text-purple-400 bg-purple-50 dark:bg-purple-900/20',
  '定语': 'text-amber-600 dark:text-amber-400 bg-amber-50 dark:bg-amber-900/20',
  '状语': 'text-teal-600 dark:text-teal-400 bg-teal-50 dark:bg-teal-900/20',
  '补语': 'text-indigo-600 dark:text-indigo-400 bg-indigo-50 dark:bg-indigo-900/20',
  '宾语补语': 'text-indigo-600 dark:text-indigo-400 bg-indigo-50 dark:bg-indigo-900/20',
  '冠词': 'text-gray-500 dark:text-gray-400 bg-gray-100 dark:bg-gray-800/50',
  '介词': 'text-gray-500 dark:text-gray-400 bg-gray-100 dark:bg-gray-800/50',
  '连词': 'text-gray-500 dark:text-gray-400 bg-gray-100 dark:bg-gray-800/50',
  '助动词': 'text-rose-600 dark:text-rose-400 bg-rose-50 dark:bg-rose-900/20',
  '情态动词': 'text-rose-600 dark:text-rose-400 bg-rose-50 dark:bg-rose-900/20',
  '否定词': 'text-gray-500 dark:text-gray-400 bg-gray-100 dark:bg-gray-800/50',
  '疑问词': 'text-amber-600 dark:text-amber-400 bg-amber-50 dark:bg-amber-900/20',
  '感叹词': 'text-amber-600 dark:text-amber-400 bg-amber-50 dark:bg-amber-900/20',
  '引导词': 'text-gray-500 dark:text-gray-400 bg-gray-100 dark:bg-gray-800/50',
  '关系代词': 'text-amber-600 dark:text-amber-400 bg-amber-50 dark:bg-amber-900/20',
  '关系副词': 'text-amber-600 dark:text-amber-400 bg-amber-50 dark:bg-amber-900/20',
  '形式主语': 'text-gray-500 dark:text-gray-400 bg-gray-100 dark:bg-gray-800/50',
  '强调部分': 'text-indigo-600 dark:text-indigo-400 bg-indigo-50 dark:bg-indigo-900/20',
  '不定式符号': 'text-gray-500 dark:text-gray-400 bg-gray-100 dark:bg-gray-800/50',
  '逻辑主语': 'text-blue-600 dark:text-blue-400 bg-blue-50 dark:bg-blue-900/20',
  '独立主格': 'text-indigo-600 dark:text-indigo-400 bg-indigo-50 dark:bg-indigo-900/20',
  '比较对象': 'text-gray-500 dark:text-gray-400 bg-gray-100 dark:bg-gray-800/50',
  '标点': 'text-gray-400 dark:text-gray-500',
}
